[project]
name = "fdtd-solver-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "numpy>=2.4.2",
    "pyevtk>=1.6.0",
    "pyvista>=0.47.0",
]
